channels:
- conda-forge
dependencies:
- python=3.10.4
- pip<=22.0.4
- pip:
  - mlflow==3.1.4
  - cloudpickle==3.1.1
  - numpy==2.2.6
  - pandas==2.3.1
  - psutil==7.0.0
  - pyarrow==20.0.0
  - scikit-learn==1.7.1
  - scipy==1.15.3
name: mlflow-env
